stages:
  - build


include:
  - component: $CI_SERVER_FQDN/homelab/ci-cd/components/dockerbuild/docker-build@0.0.7
    inputs:
      dockerfile: "./Dockerfile"
      platform: 'linux/amd64,linux/arm64'